# 数据预处理

In [74]:
import pandas as pd
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.express as px

In [75]:
data = pd.read_excel("./data/report.xlsx")
data.head()

,序号,提交答卷时间,所用时间,来源,来源详情,来自IP,总分,1、你的年级,2、您的性别：,3、你所学专业类别,...,14、其他：,15、不使用AI工具辅助学习的原因是,16、其他：,17、你认为AI工具的使用在思维深度上有什么影响（假设没有AI工具时思维深度为10）,18、面对AI技术的快速发展，你是否感到学习压力增大,19、你是否担心AI技术会取代你所学专业中的某些工作岗位,20、你认为在AI时代，以下哪几项素养对大学生最为重要,21、其他：,22、为了适应AI时代的发展，你认为可以通过哪些途径提升自己的素养,23、其他：
0,1,2025/2/6 21:48:57,40秒,手机提交,直接访问,39.144.156.195(江苏-苏州),14,大二,男,理工科,...,(跳过),(跳过),(跳过),14,是，感到很大压力,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动┋ 加强与同学、老师的交流与合作,(跳过)
1,2,2025/2/6 21:59:46,99秒,手机提交,直接访问,222.93.73.70(江苏-苏州),15,大二,男,理工科,...,(跳过),(跳过),(跳过),15,有一定压力，但还能应对,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),自主学习新知识、新技能┋ 加强与同学、老师的交流与合作,(跳过)
2,3,2025/2/7 0:34:40,84秒,手机提交,直接访问,122.193.37.82(江苏-苏州),8,大二,男,理工科,...,(跳过),(跳过),(跳过),8,有一定压力，但还能应对,不太担心，因为AI无法完全替代人类或我有其他竞争优势,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),加强与同学、老师的交流与合作,(跳过)
3,4,2025/2/8 12:33:26,120秒,手机提交,直接访问,120.219.74.205(河南-周口),15,大二,男,理工科,...,(跳过),(跳过),(跳过),15,压力不大，因为我有足够的学习资源,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋创新与创造力┋技术素养与编程能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)
4,5,2025/2/8 12:37:47,87秒,手机提交,直接访问,117.136.105.220(河南-郑州),15,大二,女,理工科,...,(跳过),(跳过),(跳过),15,有一定压力，但还能应对,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),参加相关培训课程或讲座┋自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)

In [76]:
data = data.drop(columns=["序号", "提交答卷时间", "所用时间", "来源", "来源详情", "来自IP", "总分"], axis=1)
data.head()

,1、你的年级,2、您的性别：,3、你所学专业类别,4、在过去你有使用过AI工具来辅助学习吗,5、在学习过程中，你使用AI在哪些方面提供帮助,6、其他：,7、使用AI工具后，你觉得你的学习效率有多大程度提高,8、以下哪些问题类型与你在使用AI工具时的情况类似,9、其他：,10、对于上一题中的前两类问题，你每周提问的频次大约为,...,14、其他：,15、不使用AI工具辅助学习的原因是,16、其他：,17、你认为AI工具的使用在思维深度上有什么影响（假设没有AI工具时思维深度为10）,18、面对AI技术的快速发展，你是否感到学习压力增大,19、你是否担心AI技术会取代你所学专业中的某些工作岗位,20、你认为在AI时代，以下哪几项素养对大学生最为重要,21、其他：,22、为了适应AI时代的发展，你认为可以通过哪些途径提升自己的素养,23、其他：
0,大二,男,理工科,有,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),显著提高,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或...,(跳过),每周3次以上,...,(跳过),(跳过),(跳过),14,是，感到很大压力,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动┋ 加强与同学、老师的交流与合作,(跳过)
1,大二,男,理工科,有,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）,(跳过),显著提高,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）┋概括或发散内容（帮我写摘要）,(跳过),每周3次以上,...,(跳过),(跳过),(跳过),15,有一定压力，但还能应对,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),自主学习新知识、新技能┋ 加强与同学、老师的交流与合作,(跳过)
2,大二,男,理工科,有,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）,(跳过),有一定提高,信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或发散内容（帮我写摘要）,(跳过),每周3次以上,...,(跳过),(跳过),(跳过),8,有一定压力，但还能应对,不太担心，因为AI无法完全替代人类或我有其他竞争优势,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),加强与同学、老师的交流与合作,(跳过)
3,大二,男,理工科,有,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),有一定提高,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）,(跳过),每周3次以上,...,(跳过),(跳过),(跳过),15,压力不大，因为我有足够的学习资源,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋创新与创造力┋技术素养与编程能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)
4,大二,女,理工科,有,编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),有一定提高,信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或发散内容（帮我写摘要）,(跳过),每周3次以上,...,(跳过),(跳过),(跳过),15,有一定压力，但还能应对,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),参加相关培训课程或讲座┋自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)

In [77]:
data.columns = ["grade", "gender", "major", "use AI", "usage", "other usage", "efficiency improvement", "question type", "other question type", "frequency1", "frequency2", "helpfulness", "difficulty", "other difficulty", "reasons", "other reasons", "deep mind score", "pressure", "worry", "skills", "other skills", "methods", "other methods"]
data["grade"] = data["grade"].map({"大一": 1, "大二": 2, "大三": 3, "大四及以上": 4})
data["gender"] = data["gender"].map({"男": 0, "女": 1})
data["major"] = data["major"].map({"理工科": 0, "文科": 1, "商科": 2, "医科": 3})
data["use AI"] = data["use AI"].map({"有": 1, "无": 0})
use_data = data[data["use AI"] == 1]
use_data.reset_index(inplace=True)
not_use_data = data[data["use AI"] == 0]
not_use_data.reset_index(inplace=True)
use_data.head()

,index,grade,gender,major,use AI,usage,other usage,efficiency improvement,question type,other question type,...,other difficulty,reasons,other reasons,deep mind score,pressure,worry,skills,other skills,methods,other methods
0,0,2,0,0,1,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),显著提高,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或...,(跳过),...,(跳过),(跳过),(跳过),14,是，感到很大压力,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动┋ 加强与同学、老师的交流与合作,(跳过)
1,1,2,0,0,1,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）,(跳过),显著提高,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）┋概括或发散内容（帮我写摘要）,(跳过),...,(跳过),(跳过),(跳过),15,有一定压力，但还能应对,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),自主学习新知识、新技能┋ 加强与同学、老师的交流与合作,(跳过)
2,2,2,0,0,1,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）,(跳过),有一定提高,信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或发散内容（帮我写摘要）,(跳过),...,(跳过),(跳过),(跳过),8,有一定压力，但还能应对,不太担心，因为AI无法完全替代人类或我有其他竞争优势,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),加强与同学、老师的交流与合作,(跳过)
3,3,2,0,0,1,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),有一定提高,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）,(跳过),...,(跳过),(跳过),(跳过),15,压力不大，因为我有足够的学习资源,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋创新与创造力┋技术素养与编程能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)
4,4,2,1,0,1,编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),有一定提高,信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或发散内容（帮我写摘要）,(跳过),...,(跳过),(跳过),(跳过),15,有一定压力，但还能应对,有些担心，但认为还有时间调整,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),参加相关培训课程或讲座┋自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)

In [78]:
use_data["efficiency improvement"] = use_data["efficiency improvement"].map({"(跳过)": np.nan, "没有提高反而下降": 0, "提高不明显": 1, "有一定提高": 2, "显著提高": 3})
use_data["frequency1"] = use_data["frequency1"].map({"极少或从不": 0, "每周1次左右": 1, "每周3次以上": 2, "≥每天1次": 3})
use_data["frequency2"] = use_data["frequency2"].map({"极少或从不": 0, "每周1次左右": 1, "每周3次以上": 2, "≥每天1次": 3})
use_data["helpfulness"] = use_data["helpfulness"].map({"没有帮助": 0, "帮助不大": 1, "有一定帮助": 2, "是，有很大帮助": 3})
use_data["difficulty"] = use_data["difficulty"].map({"技术操作复杂，难以掌握": 1, "信息过载，难以筛选有效信息": 2, "依赖AI，导致自己思考减少": 3, "担心数据隐私和安全问题": 4, "其他（请说明）__________": 5})
use_data["pressure"] = use_data["pressure"].map({"没有感到压力，因为我对未来有信心": 0, "压力不大，因为我有足够的学习资源": 1, "有一定压力，但还能应对": 2, "是，感到很大压力": 3})
use_data["worry"] = use_data["worry"].map({"完全不担心": 0, "不太担心，因为AI无法完全替代人类或我有其他竞争优势": 1, "有些担心，但认为还有时间调整": 2, "非常担心，认为可能性很大": 3})
use_data = use_data.drop(columns=["reasons", "other reasons"], axis=1)
use_data.head()

C:\Users\Ignorant\AppData\Local\Temp\ipykernel_45060\700464939.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Ignorant\AppData\Local\Temp\ipykernel_45060\700464939.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Ignorant\AppData\Local\Temp\ipykernel_45060\700464939.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Ignorant\AppData\Local\Temp\ipykernel_45060\700464939.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Ignorant\AppData\Local\Temp\ipykernel_45060\700464939.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Ignorant\AppData\Local\Temp\ipykernel_45060\700464939.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Ignorant\AppData\Local\Temp\ipykernel_45060\700464939.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,index,grade,gender,major,use AI,usage,other usage,efficiency improvement,question type,other question type,...,helpfulness,difficulty,other difficulty,deep mind score,pressure,worry,skills,other skills,methods,other methods
0,0,2,0,0,1,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),3.0,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或...,(跳过),...,3,2,(跳过),14,3,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动┋ 加强与同学、老师的交流与合作,(跳过)
1,1,2,0,0,1,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）,(跳过),3.0,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）┋概括或发散内容（帮我写摘要）,(跳过),...,2,2,(跳过),15,2,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),自主学习新知识、新技能┋ 加强与同学、老师的交流与合作,(跳过)
2,2,2,0,0,1,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）,(跳过),2.0,信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或发散内容（帮我写摘要）,(跳过),...,2,3,(跳过),8,2,1,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),加强与同学、老师的交流与合作,(跳过)
3,3,2,0,0,1,智能辅导（如AI助教、在线答疑等）┋编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),2.0,解题（这道题怎么做？）┋信息检索（什么是…（某种观念等）？）,(跳过),...,3,3,(跳过),15,1,2,信息筛选与批判性思维能力┋创新与创造力┋技术素养与编程能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)
4,4,2,1,0,1,编程辅助（如代码补全、语法检查等）┋学术问题搜索与引用,(跳过),2.0,信息检索（什么是…（某种观念等）？）┋启发（我还能做什么？）┋概括或发散内容（帮我写摘要）,(跳过),...,2,2,(跳过),15,2,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),参加相关培训课程或讲座┋自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)

In [79]:
usages = ["智能辅导（如AI助教、在线答疑等）", "编程辅助（如代码补全、语法检查等）", "学术问题搜索与引用"]
use_data.insert(5, "智能辅导（如AI助教、在线答疑等）", 0)
use_data.insert(6, "编程辅助（如代码补全、语法检查等）", 0)
use_data.insert(7, "学术问题搜索与引用", 0)
for i, usage, in enumerate(use_data["usage"].tolist()):
    usage = usage.split("┋")
    for u in usage:
        if u in usages:
            use_data.loc[i, u] = 1
use_data = use_data.drop(columns=["usage"], axis=1)
use_data = use_data.rename(columns={"智能辅导（如AI助教、在线答疑等）": "智能辅导", "编程辅助（如代码补全、语法检查等）": "编程辅助", "学术问题搜索与引用": "学术问题搜索与引用"})
use_data.head()

,index,grade,gender,major,use AI,智能辅导,编程辅助,学术问题搜索与引用,other usage,efficiency improvement,...,helpfulness,difficulty,other difficulty,deep mind score,pressure,worry,skills,other skills,methods,other methods
0,0,2,0,0,1,1,1,1,(跳过),3.0,...,3,2,(跳过),14,3,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动┋ 加强与同学、老师的交流与合作,(跳过)
1,1,2,0,0,1,1,1,0,(跳过),3.0,...,2,2,(跳过),15,2,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),自主学习新知识、新技能┋ 加强与同学、老师的交流与合作,(跳过)
2,2,2,0,0,1,1,1,0,(跳过),2.0,...,2,3,(跳过),8,2,1,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),加强与同学、老师的交流与合作,(跳过)
3,3,2,0,0,1,1,1,1,(跳过),2.0,...,3,3,(跳过),15,1,2,信息筛选与批判性思维能力┋创新与创造力┋技术素养与编程能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)
4,4,2,1,0,1,0,1,1,(跳过),2.0,...,2,2,(跳过),15,2,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),参加相关培训课程或讲座┋自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)

In [80]:
questions = ["解题（这道题怎么做？）", "信息检索（什么是…（某种观念等）？）", "启发（我还能做什么？）", "概括或发散内容（帮我写摘要）", "无目的地畅聊（你们AI究竟有没有自我意识？）"]
use_data.insert(11, "解题（这道题怎么做？）", 0)
use_data.insert(12, "信息检索（什么是…（某种观念等）？）", 0)
use_data.insert(13, "启发（我还能做什么？）", 0)
use_data.insert(14, "概括或发散内容（帮我写摘要）", 0)
use_data.insert(15, "无目的地畅聊（你们AI究竟有没有自我意识？）", 0)
for i, question, in enumerate(use_data["question type"].tolist()):
    question = question.split("┋")
    for q in question:
        if q in questions:
            use_data.loc[i, q] = 1
use_data = use_data.drop(columns=["question type"], axis=1)
use_data = use_data.rename(columns={"解题（这道题怎么做？）": "解题", "信息检索（什么是…（某种观念等）？）": "信息检索", "启发（我还能做什么？）": "启发", "概括或发散内容（帮我写摘要）": "概括或发散内容", "无目的地畅聊（你们AI究竟有没有自我意识？）": "无目的地畅聊"})
use_data.head()

,index,grade,gender,major,use AI,智能辅导,编程辅助,学术问题搜索与引用,other usage,efficiency improvement,...,helpfulness,difficulty,other difficulty,deep mind score,pressure,worry,skills,other skills,methods,other methods
0,0,2,0,0,1,1,1,1,(跳过),3.0,...,3,2,(跳过),14,3,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动┋ 加强与同学、老师的交流与合作,(跳过)
1,1,2,0,0,1,1,1,0,(跳过),3.0,...,2,2,(跳过),15,2,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),自主学习新知识、新技能┋ 加强与同学、老师的交流与合作,(跳过)
2,2,2,0,0,1,1,1,0,(跳过),2.0,...,2,3,(跳过),8,2,1,信息筛选与批判性思维能力┋持续学习的能力与意愿┋创新与创造力,(跳过),加强与同学、老师的交流与合作,(跳过)
3,3,2,0,0,1,1,1,1,(跳过),2.0,...,3,3,(跳过),15,1,2,信息筛选与批判性思维能力┋创新与创造力┋技术素养与编程能力,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)
4,4,2,1,0,1,0,1,1,(跳过),2.0,...,2,2,(跳过),15,2,2,信息筛选与批判性思维能力┋持续学习的能力与意愿┋跨领域合作与沟通能力,(跳过),参加相关培训课程或讲座┋自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)

In [81]:
skills = ["信息筛选与批判性思维能力", "持续学习的能力与意愿", "职业道德与伦理意识", "跨领域合作与沟通能力", "创新与创造力", "技术素养与编程能力"]
use_data.insert(25, "信息筛选与批判性思维能力", 0)
use_data.insert(26, "持续学习的能力与意愿", 0)
use_data.insert(27, "职业道德与伦理意识", 0)
use_data.insert(28, "跨领域合作与沟通能力", 0)
use_data.insert(29, "创新与创造力", 0)
use_data.insert(30, "技术素养与编程能力", 0)
for i, skill, in enumerate(use_data["skills"].tolist()):
    skill = skill.split("┋")
    for s in skill:
        if s in skills:
            use_data.loc[i, s] = 1
use_data = use_data.drop(columns=["skills"], axis=1)
use_data.head()

,index,grade,gender,major,use AI,智能辅导,编程辅助,学术问题搜索与引用,other usage,efficiency improvement,...,worry,信息筛选与批判性思维能力,持续学习的能力与意愿,职业道德与伦理意识,跨领域合作与沟通能力,创新与创造力,技术素养与编程能力,other skills,methods,other methods
0,0,2,0,0,1,1,1,1,(跳过),3.0,...,2,1,1,0,1,0,0,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动┋ 加强与同学、老师的交流与合作,(跳过)
1,1,2,0,0,1,1,1,0,(跳过),3.0,...,2,1,1,0,0,1,0,(跳过),自主学习新知识、新技能┋ 加强与同学、老师的交流与合作,(跳过)
2,2,2,0,0,1,1,1,0,(跳过),2.0,...,1,1,1,0,0,1,0,(跳过),加强与同学、老师的交流与合作,(跳过)
3,3,2,0,0,1,1,1,1,(跳过),2.0,...,2,1,0,0,0,1,1,(跳过),自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)
4,4,2,1,0,1,0,1,1,(跳过),2.0,...,2,1,1,0,1,0,0,(跳过),参加相关培训课程或讲座┋自主学习新知识、新技能┋参与科研项目或实践活动,(跳过)

In [82]:
methods = ["参加相关培训课程或讲座", "自主学习新知识、新技能", "参与科研项目或实践活动", "加强与同学、老师的交流与合作", "寻求专业导师或行业专家的指导"]
use_data.insert(32, "参加相关培训课程或讲座", 0)
use_data.insert(33, "自主学习新知识、新技能", 0)
use_data.insert(34, "参与科研项目或实践活动", 0)
use_data.insert(35, "加强与同学、老师的交流与合作", 0)
use_data.insert(36, "寻求专业导师或行业专家的指导", 0)
for i, method, in enumerate(use_data["methods"].tolist()):
    method = method.split("┋")
    for m in method:
        m = m.strip()
        if m in methods:
            use_data.loc[i, m] = 1
use_data = use_data.drop(columns=["methods"], axis=1)
use_data.head()

,index,grade,gender,major,use AI,智能辅导,编程辅助,学术问题搜索与引用,other usage,efficiency improvement,...,跨领域合作与沟通能力,创新与创造力,技术素养与编程能力,other skills,参加相关培训课程或讲座,自主学习新知识、新技能,参与科研项目或实践活动,加强与同学、老师的交流与合作,寻求专业导师或行业专家的指导,other methods
0,0,2,0,0,1,1,1,1,(跳过),3.0,...,1,0,0,(跳过),0,1,1,1,0,(跳过)
1,1,2,0,0,1,1,1,0,(跳过),3.0,...,0,1,0,(跳过),0,1,0,1,0,(跳过)
2,2,2,0,0,1,1,1,0,(跳过),2.0,...,0,1,0,(跳过),0,0,0,1,0,(跳过)
3,3,2,0,0,1,1,1,1,(跳过),2.0,...,0,1,1,(跳过),0,1,1,0,0,(跳过)
4,4,2,1,0,1,0,1,1,(跳过),2.0,...,1,0,0,(跳过),1,1,1,0,0,(跳过)

In [83]:
heatmap_data = use_data.drop(columns=["index", "use AI", "other usage", "other question type", "other difficulty", "other skills", "other methods"], axis=1)
heatmap_data = (heatmap_data - heatmap_data.min()) / (heatmap_data.max() - heatmap_data.min())
heatmap_data.head()

,grade,gender,major,智能辅导,编程辅助,学术问题搜索与引用,efficiency improvement,解题,信息检索,启发,...,持续学习的能力与意愿,职业道德与伦理意识,跨领域合作与沟通能力,创新与创造力,技术素养与编程能力,参加相关培训课程或讲座,自主学习新知识、新技能,参与科研项目或实践活动,加强与同学、老师的交流与合作,寻求专业导师或行业专家的指导
0,0.333333,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
1,0.333333,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.333333,0.0,0.0,1.0,1.0,0.0,0.5,0.0,1.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.333333,0.0,0.0,1.0,1.0,1.0,0.5,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0
4,0.333333,1.0,0.0,0.0,1.0,1.0,0.5,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0

In [84]:
fig = px.imshow(heatmap_data.corr().values.round(3), x=heatmap_data.columns, y=heatmap_data.columns, labels=dict(color="Correlation"), color_continuous_scale="RdBu_r", text_auto=True)
fig.update_layout(title={"text": "Correlation Matrix Between Variables", "xanchor": "center", "yanchor": "top", "x": 0.5, "y": 0.98}, height=1300)
fig.show()

In [85]:
use_data["grade"].value_counts()

grade
2    18
1    11
3     9
4     7
Name: count, dtype: int64

In [86]:
use_data["gender"].value_counts()

gender
0    25
1    20
Name: count, dtype: int64

In [87]:
use_data["major"].value_counts()

major
0    23
1     9
2     8
3     5
Name: count, dtype: int64

# 变量各自的分布

In [88]:
fig = make_subplots(rows=2, cols=2, subplot_titles=["年级分布", "性别分布", "专业分布", "AI 使用情况"], 
                    specs=[[{"type": "domain"}, {"type": "domain"}],
                           [{"type": "domain"}, {"type": "domain"}]])
fig.add_trace(go.Pie(labels=["大一", "大二", "大三", "大四及以上"], values=data["grade"].value_counts().tolist()), row=1, col=1)
fig.add_trace(go.Pie(labels=["男", "女"], values=data["gender"].value_counts().tolist()), row=1, col=2)
fig.add_trace(go.Pie(labels=["理工科", "文科", "商科", "医科"], values=data["major"].value_counts().tolist()), row=2, col=1)
fig.add_trace(go.Pie(labels=["有", "无"], values=data["use AI"].value_counts().tolist()), row=2, col=2)
fig.update_layout(height=800)
fig.show()

In [89]:
x = ["智能辅导", "编程辅助", "学术问题搜索与引用", "其他"]
y = []
for i in x[:-1]:
    y.append(use_data[i].sum())
count = 0
for i in use_data["other usage"].tolist():
    if i != "(跳过)":
        count += 1
y.append(count)
fig = px.pie(names=x, values=y, hole=0.5)
fig.update_layout(title={
    "text": "AI 使用情况",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [90]:
x = ["显著提高", "有一定提高", "提高不明显", "没有提高反而下降"]
y = [0, 0, 0, 0]
for i in use_data["efficiency improvement"].tolist():
    y[3 - int(i)] += 1
fig = px.bar(x=x, y=y, labels={"x": "效率提升程度", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "效率提升情况",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [91]:
x = ["解题", "信息检索", "启发", "概括或发散内容", "无目的地畅聊"]
y = []
for i in x:
    y.append(use_data[i].sum())
fig = px.bar(x=x, y=y, labels={"x": "问题类型", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "问题类型分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [92]:
x = ["极少或从不", "每周1次左右", "每周3次以上", "≥每天1次"]
y = [0, 0, 0, 0]
for i in use_data["frequency1"].tolist():
    y[int(i)] += 1
fig = px.bar(x=x, y=y, labels={"x": "问题频率", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "前两类问题的频率分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [93]:
x = ["极少或从不", "每周1次左右", "每周3次以上", "≥每天1次"]
y = [0, 0, 0, 0]
for i in use_data["frequency2"].tolist():
    y[int(i)] += 1
fig = px.bar(x=x, y=y, labels={"x": "问题频率", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "后三类问题的频率分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [94]:
x = ["没有帮助", "帮助不大", "有一定帮助", "是，有很大帮助"]
y = [0, 0, 0, 0]
for i in use_data["helpfulness"].tolist():
    y[int(i)] += 1
fig = px.bar(x=x, y=y, labels={"x": "问题帮助程度", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "问题帮助程度分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [95]:
x = ["技术操作复杂，难以掌握", "信息过载，难以筛选有效信息", "依赖AI，导致自己思考减少", "担心数据隐私和安全问题", "其他（请说明）__________"]
y = [0, 0, 0, 0, 0]
for i in use_data["difficulty"].tolist():
    y[int(i) - 1] += 1
x[-1] = "其他"
fig = px.bar(x=x, y=y, labels={"x": "困难", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "最常遇到的困难的分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [96]:
fig = px.histogram(use_data, x="deep mind score", text_auto=True, nbins=10)
fig.update_layout(title={
    "text": "思维深度直方图",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
}, xaxis_title="思维深度", yaxis_title="人数")
fig.show()

In [97]:
x = ["是，感到很大压力", "有一定压力，但还能应对", "压力不大，因为我有足够的学习资源", "没有感到压力，因为我对未来有信心"]
y = [0, 0, 0, 0]
for i in use_data["pressure"].tolist():
    y[3 - int(i)] += 1
fig = px.bar(x=x, y=y, labels={"x": "学习压力", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "学习压力程度分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [98]:
x = ["完全不担心", "不太担心，因为AI无法完全替代人类或我有其他竞争优势", "有些担心，但认为还有时间调整", "非常担心，认为可能性很大"]
y = [0, 0, 0, 0]
for i in use_data["worry"].tolist():
    y[3 - int(i)] += 1
x.reverse()
fig = px.bar(x=x, y=y, labels={"x": "焦虑程度", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "焦虑程度分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [99]:
x = ["信息筛选与批判性思维能力", "持续学习的能力与意愿", "职业道德与伦理意识", "跨领域合作与沟通能力", "创新与创造力", "技术素养与编程能力", "其他"]
y = []
for i in x[:-1]:
    y.append(use_data[i].sum())
count = 0
for i in use_data["other skills"].tolist():
    if i != "(跳过)":
        count += 1
y.append(count)
fig = px.pie(names=x, values=y, hole=0.5)
fig.update_layout(title={
    "text": "对大学生最为重要的素养分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [100]:
x = ["参加相关培训课程或讲座", "自主学习新知识、新技能", "参与科研项目或实践活动", "加强与同学、老师的交流与合作", "寻求专业导师或行业专家的指导", "其他"]
y = []
for i in x[:-1]:
    y.append(use_data[i].sum())
y.append(0)
fig = px.bar(x=x, y=y, labels={"x": "提升自身素养途径", "y": "人数"}, text_auto=True)
fig.update_layout(title={
    "text": "提升自身素养途径分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

# 变量之间的关系

In [101]:
temp = use_data.query("编程辅助 == 1")
fig = make_subplots(rows=1, cols=2, subplot_titles=["选择编程辅助的人在专业上的分布", "选择编程辅助的人在年级上的分布"])
fig.add_trace(go.Bar(x=["理工科", "文科", "商科", "医科"], y=temp["major"].value_counts() / len(temp["major"])), row=1, col=1)
fig.add_trace(go.Bar(x=["大一", "大二", "大三", "大四及以上"], y=temp["grade"].value_counts() / len(temp["grade"])), row=1, col=2)
fig.update_layout(xaxis_title="专业", yaxis_title="人数占比")
fig.show()

In [114]:
temp = use_data.query("解题 == 1")
fig = px.pie(names=["男", "女"], values=temp["gender"].value_counts(), hole=0.5)
fig.update_layout(title={
    "text": "选择解题的人在性别上的分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [103]:
temp = use_data.sort_values("frequency1", ascending=False)
temp["major"] = temp["major"].map({0: "理工科", 1: "文科", 2: "商科", 3: "医科"})
fig = px.bar(temp, x="major", y="use AI", color="frequency1", labels={"use AI": "人数", "major": "专业", "frequency1": "频率"})
fig.update_layout(title={
    "text": "选择前两类问题的人在专业上的分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [104]:
temp = use_data.sort_values("frequency2", ascending=False)
temp["major"] = temp["major"].map({0: "理工科", 1: "文科", 2: "商科", 3: "医科"})
fig = px.bar(temp, x="major", y="use AI", color="frequency2", labels={"use AI": "人数", "major": "专业", "frequency2": "频率"})
fig.update_layout(title={
    "text": "选择后三类问题的人在专业上的分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [105]:
fig = go.Figure()
temp = use_data.query("frequency1 == 3")
y = []
methods = ["参加相关培训课程或讲座", "自主学习新知识、新技能", "参与科研项目或实践活动", "加强与同学、老师的交流与合作", "寻求专业导师或行业专家的指导"]
for method in methods:
    y.append(temp[method].sum())
fig.add_trace(go.Bar(x=methods, y=y, name="≥每天1次"))
temp = use_data.query("frequency1 == 2")
y = []
for method in methods:
    y.append(temp[method].sum())
fig.add_trace(go.Bar(x=methods, y=y, name="每周3次以上"))
temp = use_data.query("frequency1 == 1")
y = []
for method in methods:
    y.append(temp[method].sum())
fig.add_trace(go.Bar(x=methods, y=y, name="每周1次左右"))
temp = use_data.query("frequency1 == 0")
y = []
for method in methods:
    y.append(temp[method].sum())
fig.add_trace(go.Bar(x=methods, y=y, name="极少或从不"))
fig.update_layout(title={
    "text": "选择前两类问题的频率与提升自身素养途径之间的关系",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
}, barmode="stack", yaxis_title="人数")
fig.show()

In [106]:
fig = go.Figure()
temp = use_data.query("frequency2 == 3")
y = []
methods = ["参加相关培训课程或讲座", "自主学习新知识、新技能", "参与科研项目或实践活动", "加强与同学、老师的交流与合作", "寻求专业导师或行业专家的指导"]
for method in methods:
    y.append(temp[method].sum())
fig.add_trace(go.Bar(x=methods, y=y, name="≥每天1次"))
temp = use_data.query("frequency2 == 2")
y = []
for method in methods:
    y.append(temp[method].sum())
fig.add_trace(go.Bar(x=methods, y=y, name="每周3次以上"))
temp = use_data.query("frequency2 == 1")
y = []
for method in methods:
    y.append(temp[method].sum())
fig.add_trace(go.Bar(x=methods, y=y, name="每周1次左右"))
temp = use_data.query("frequency2 == 0")
y = []
for method in methods:
    y.append(temp[method].sum())
fig.add_trace(go.Bar(x=methods, y=y, name="极少或从不"))
fig.update_layout(title={
    "text": "选择后三类问题的频率与提升自身素养途径之间的关系",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
}, barmode="stack", yaxis_title="人数")
fig.show()

In [107]:
fig = go.Figure()
x = ["是，有很大帮助", "有一定帮助", "帮助不大"]
temp = use_data.query("gender == 0")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="男"))
temp = use_data.query("gender == 1")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="女"))
fig.update_layout(title={
    "text": "对发现新的兴趣的帮助在性别上的分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.9,
}, barmode="group", yaxis_title="人数占比")
fig.show()

In [108]:
fig = go.Figure()
temp = use_data.query("major == 0")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="理工科"))
temp = use_data.query("major == 1")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="文科"))
temp = use_data.query("major == 2")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="商科"))
temp = use_data.query("major == 3")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="医科"))
fig.update_layout(title={
    "text": "对发现新的兴趣的帮助在专业上的分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.9,
}, barmode="group", yaxis_title="人数占比")
fig.show()

In [109]:
fig = go.Figure()
temp = use_data.query("grade == 1")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="大一"))
temp = use_data.query("grade == 2")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="大二"))
temp = use_data.query("grade == 3")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="大三"))
temp = use_data.query("grade == 4")
fig.add_trace(go.Bar(x=x, y=temp["helpfulness"].value_counts() / len(temp["helpfulness"]), name="大四及以上"))
fig.update_layout(title={
    "text": "对发现新的兴趣的帮助在年级上的分布",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.9,
}, barmode="group", yaxis_title="人数占比")
fig.show()

In [110]:
grades = ["大一", "大二", "大三", "大四及以上"]
r = []
for i, grade in enumerate(grades):
    temp = use_data.query(f"grade == {i+1}")
    r.append(temp["deep mind score"].mean())
fig = px.line_polar(r=r, theta=grades, line_close=True)
fig.update_layout(polar={
    "radialaxis": {
        "visible": True,
        "range": [0, 20]
    },
}, title={
    "text": "使用 AI 工具后不同年级的平均思维深度",
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.97,
}, polar_radialaxis_visible=True, polar_angularaxis_rotation=90, height=500)
fig.show()

In [115]:
temp = use_data.query("编程辅助 == 1")
fig = px.pie(names=["否", "是"], values=temp["寻求专业导师或行业专家的指导"].value_counts(), title="选择编程辅助的人是否认为通过寻求专业导师或行业专家的指导可以提升自己的素养", hole=0.5)
fig.update_layout(title={
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.5,
    "y": 0.95,
})
fig.show()

In [121]:
temp = use_data.query("学术问题搜索与引用 == 1")
fig = px.pie(names=["没有感到压力，因为我对未来有信心", "压力不大，因为我有足够的学习资源", "有一定压力，但还能应对", "是，感到很大压力"], values=temp["pressure"].value_counts(), title="利用 AI 工具进行学术问题搜索与引用的人的学习压力", hole=0.5)
fig.update_layout(title={
    "xanchor": "center",
    "yanchor": "top",
    "x": 0.38,
    "y": 0.95,
})
fig.show()

In [113]:
x = ["没有提高反而下降", "提高不明显", "有一定提高", "显著提高"]
y = np.zeros(4)
for i in use_data["efficiency improvement"].tolist():
    y[int(i)] += 1
fig = px.line(x=x, y=y / y.sum(), title="效率提升程度与焦虑程度之间的关系")
fig.update_layout(xaxis_title="效率提升程度", yaxis_title="平均焦虑程度")
fig.show()