In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
host_df = pd.read_csv("./data/summerOly_hosts.csv")
host_df = host_df.query("Year != 1916 and Year != 1940 and Year != 1944")
hosts = host_df["Host"].values
for i, host in enumerate(hosts):
    if '(' in host:
        host = host.split(' (')[0]
    hosts[i] = host.split('\xa0')[-1]
host_df["Host"] = hosts
host_df.head()
host_df.head()

   Year            Host
0  1896          Greece
1  1900          France
2  1904   United States
3  1908  United Kingdom
4  1912          Sweden

In [5]:
medal_df = pd.read_csv("./data/summerOly_medal_counts.csv")
countries = medal_df["NOC"].values
for i, country in enumerate(countries):
    countries[i] = country.strip()
medal_df["NOC"] = countries
medal_df.head()

   Rank            NOC  Gold  Silver  Bronze  Total  Year
0     1  United States    11       7       2     20  1896
1     2         Greece    10      18      19     47  1896
2     3        Germany     6       5       2     13  1896
3     4         France     5       4       2     11  1896
4     5  Great Britain     2       3       2      7  1896

In [28]:
import plotly.io as pio
import random


host_countries = host_df["Host"].unique()
medal_df = medal_df.query("NOC in @host_countries")
fig = go.Figure()
for country in host_countries:
    medal_by_country = medal_df.query("NOC == @country").sort_values("Year")
    fig.add_trace(go.Scatter(x=medal_by_country["Year"], y=medal_by_country["Total"], name=country, mode="lines+markers"))
for country in host_countries:
    host_by_country = host_df.query("Host == @country")
    years = host_by_country["Year"].sort_values()
    medal_by_country = medal_df.query("NOC == @country and Year in @years").sort_values("Year")
    fig.add_trace(go.Scatter(x=years, y=medal_by_country["Total"], showlegend=False, marker={"color": "red", "size": 10}, mode="markers"))
additional_colors = tuple()
for _ in range(len(host_countries) - 10):
    r = random.randint(0, 255)
    g = random.randint(0, 255)
    b = random.randint(0, 255)
    color = f"#{r:02x}{g:02x}{b:02x}"
    additional_colors += (color, )
plotly_template = pio.templates["plotly"]
pio.templates["draft"] = plotly_template
basic_colors = pio.templates["draft"]["layout"]["colorway"]
pio.templates["draft"]["layout"]["colorway"] = basic_colors + additional_colors
fig.update_layout(title={
    "text": "Summer Olympics Medal Counts by Host Country",
    "x": 0.5,
    "y": 0.95,
    "xanchor": "center",
    "yanchor": "top",
}, height=600, colorway=basic_colors+additional_colors)
fig.show()

In [29]:
host_countries = host_df["Host"].unique()
medal_df = medal_df.query("NOC in @host_countries")
fig = go.Figure()
for country in host_countries:
    medal_by_country = medal_df.query("NOC == @country").sort_values("Year")
    fig.add_trace(go.Scatter(x=medal_by_country["Year"], y=medal_by_country["Gold"], name=country, mode="lines+markers"))
for country in host_countries:
    host_by_country = host_df.query("Host == @country")
    years = host_by_country["Year"].sort_values()
    medal_by_country = medal_df.query("NOC == @country and Year in @years").sort_values("Year")
    fig.add_trace(go.Scatter(x=years, y=medal_by_country["Gold"], showlegend=False, marker={"color": "red", "size": 10}, mode="markers"))
fig.update_layout(title={
    "text": "Summer Olympics Gold Medal Counts by Host Country",
    "x": 0.5,
    "y": 0.95,
    "xanchor": "center",
    "yanchor": "top",
}, height=600, colorway=basic_colors+additional_colors)
fig.show()